### PR TITLE
Add PolygonTiler

### PR DESCRIPTION
**Pull request by FObermaier**
Change some type checks to interfaces
Fix/Add LineStringTilerTest

Unit test for polygon is missing, perhaps you have some data to prove.

### CODE REVIEW

**Comment by FObermaier** [comment]
Here is a picture of the result from `PolygonTilerTests.TestAurichAtZoom12` test:
grafik

**Comment by xivk** [comment]
Ok, wow! Thanks, this looks great. I will have a look asap... :+1:

**Comment by xivk** [comment]
This is interesting, can you explain this one? 

`var prep = Geometries.Prepared.PreparedGeometryFactory.Prepare(polygon);`

Is it something I best do with for example linestrings as well?

**Comment by FObermaier** [comment]
`PreparedGeometry` is optimized for one against many predicate checks. Generally speaking, it would solve the problem for `LineString` and `Point` as well, I don't know if it preforms better than the algorithm you implemented. We'd have to check that.
Unless you are having issues with it (artefacts), than I'd go with `PreparedGeometry` right away.

**Pull request merged**
